### ISSUE TITLE
Use Test.Hspec.Core.Format

### ISSUE THREAD

**Issue by sol** [freckle/hspec-junit-formatter#6]
`hspec-2.8.0` exposes `Test.Hspec.Core.Format`.  This is very similar to what @eborden suggested in https://github.com/hspec/hspec/issues/411 and might be a better fit to implement `hspec-junit-formatter`.

NB: Please also feel free to add links to `hspec-junit-formatter` and `hspec-expectations-json` to the Hspec docs.

**Comment by eborden** [comment]
Thanks for the update @sol. I'll put a task in the backlog to explore utilizing `Text.Hspec.Core.Format`.

**Comment by eborden** [comment]
I did a quick spike. There is still validation left to do, but the results are promising. A ton of indirection made necessary by the previous DSL has been removed.

https://github.com/freckle/hspec-junit-formatter/compare/eborden/utilize-new-hspec-format
